version: '3.8'

services:
  twitch-discord-bot:
    build: .
    container_name: twitch-discord-bot
    restart: unless-stopped

    # Environment variables from .env file
    env_file:
      - .env

    # Port mapping for webhook server
    ports:
      - "${WEBHOOK_PORT:-8081}:${WEBHOOK_PORT:-8081}"

    # Volume mounts for persistent data
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs

    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M